```{r include=FALSE}
library(rethinking)
library(brms)
library(dplyr, quietly = TRUE)
library(tidyr, quietly = TRUE)
library(tidybayes, quietly = TRUE)
library(ggdist, quietly = TRUE)
library(patchwork, quietly = TRUE)
library(paletteer, quietly = TRUE)
```


# Multivariate Linear Models {#multivariate}


## 5E1 {-}

1. **Not** multiple linear, just univariate regression.
2. Multiple linear with 2 variables $x_i$ and $z_i$
3. **Not** multiple linear, just univariate
4. Multiple linear

## 5E2 {-}

In section 5.1.2 the notion of control is related to conditional independencies
where the question becomes *is there any additional values in knowing a variable,
once I already know the other variables?* (p.131).

Also see Rethinking box in section 5.1.2 on the usage of the word *control*.

The control can be executed by using *predictor residual plots* or *counterfactual plots*
as described in section 5.1.5.

The model is

$$
\begin{align*}
diversity_i &\sim Normal(\mu_i, \sigma)\\
\mu_i &= \alpha + \beta_1 \cdot latitude_i + \beta_2 \cdot plantdiversity_i\\
\alpha &\sim Normal(0, 1)\\
\beta_1 &\sim Normal(0, 1)\\
\beta_2 &\sim Normal(0, 1)\\
\sigma &\sim Uniform(0, 1)
\end{align*}
$$

## 5E3 {-}

See overthinking box in section 5.1.5.2 where spurious relationship is when
a predictor influences both the outcome and another predictor as in the divorce 
example in section 5.1.  See pratice 5M1.

A masked relationship is when there are 2 predictors that are correlated with each other,
However one is positively correlated with the outcome, the other one is negatively 
correlated with the outcome. See beginning of section 5.2 for description. See practice 5M2.

This practice is closely related to section 5.2 *Masked relationship*.

Model is 

$$
\begin{align*}
phd_i &\sim \mathcal{N}(\mu_i, \sigma) \\
\mu_i &= \alpha + \beta_1 \cdot funding_i + \beta_2 \cdot size_i \\
\alpha &\sim Normal(0, 1)\\
\beta_1 &\sim Normal(0, 1)\\
\beta_2 &\sim Normal(0, 1)\\
\sigma &\sim Uniform(0, 1)
\end{align*}
$$

The slopes should be positive.

## 5E4 {-}

Let $k$ be the number of categories, only need to have $k-1$ variables since
the intercept represents the $k^{th}$ category, hence model 1, 3, 4 are equivalent.
See explanantion in first paragraph of section 5.3.2.

Model 5 is also inferentially equivalent as it uses
a re-parametrization which was explained in the first edition, edition of 2016. 
(overthinking box of section 5.4.1 of the 2016 edition)


## 5M1 {-}

A spurious correlation where an outcome is correlated with 2 predictors but
when both predictors are entered the correlation between the outcome and one of
the predictors vanishes.

For example the performance of a manufacturing plant increases when you buy machineries
and invest in training.  But if the training is on how to sue the machineries
that were just acquired then it should give a spurious relationship.


## 5M2 {-}

The profitability of an enterprise will increase depending on how much raw material
it can process but inversely depending on how much waste is generated.


## 5M3 {-}

More divorces could lead to more remarriage and therefore contribute to an increase
in marriage rate.

## 5M4 {-}

Not done

## 5M5 {-}

Not done

## 5H1 {-}

The conditional independency is *M is independent of D conditional on A* as it 
is a *chain*.

The data does support it as there was no relation be between  M and D once we remove
the influence of A.  See Figure 5.7 in section 5.1.5.3

## 5H2 {-}

