```{r include=FALSE}
library(rethinking)
library(brms)
library(dplyr, quietly = TRUE)
library(tidyr, quietly = TRUE)
library(tidybayes, quietly = TRUE)
library(dagitty, quietly = TRUE)
library(ggdag, quietly = TRUE)
library(ggdist, quietly = TRUE)
library(patchwork, quietly = TRUE)
library(paletteer, quietly = TRUE)
```


# Structural Causal Models {#SCM}


## 6E1 {-}

* Multicollinearity, section 6.1
* Post-treatment bias, section 6.2
* Collider bias, section 6.3

## 6E2 {-}




## 6H1 {-}

```{r}
message("TODO: 6H1")
```


## 6H2 {-}

See practice 7H5 in chapter 7 for corresponding exercises.

```{r}
data(foxes)
d <- foxes %>%
  mutate(
    W = scale(as.vector(weight)),
    A = scale(as.vector(area)),
    S = scale(as.vector(groupsize))
  )
skimr::skim(d)
```

### 6H2 a) By territory area size {-}

$$
\begin{align*}
W_i &\sim \mathcal{N}(\mu_i, \sigma) \\
\mu_i &= \alpha + \beta \cdot A_i \\
\alpha &\sim \mathcal{N}(0, 0.5) \\
\beta &\sim \mathcal{N}(0, 0.2) \\
\sigma &\sim \mathcal{HalfCauchy}(0, 1)
\end{align*}
$$

and the fit

```{r}
a_file <- here::here("fits", "b06H02a.rds")
b06H02a <- readRDS(file = a_file)
# b06H02a <- brm(
#   data = d,
#   formula = W ~ 1 + A,
#   family = gaussian,
#   prior = c(
#     prior(normal(0, 0.5), class = Intercept),
#     prior(normal(0, 0.2), class = b),
#     prior(cauchy(0, 1), class = sigma)
#   ),
#   iter = 2000, warmup = 1000, chains = 4, core = detectCores(),
#   seed = 6
# )
# saveRDS(b06H02a, file = a_file)
summary(b06H02a)
```

and create the full data for plotting

```{r}
samples <- list()
samples$fitted <- fitted(b06H02a) %>%
  as.data.frame() %>%
  rename(
    fit = Estimate,
    fit_err = Est.Error,
    fit_Q2.5 = Q2.5,
    fit_Q97.5 = Q97.5)

samples$predict <- predict(b06H02a) %>%
  data.frame() %>%
  rename(
    pred = Estimate,
    pred_err = Est.Error,
    pred_Q2.5 = Q2.5,
    pred_Q97.5 = Q97.5,)

samples$data <- d %>%
  bind_cols(samples$fitted) %>%
  bind_cols(samples$predict)
```



```{r}
ggplot(data = samples$data, mapping = aes(x = A, y = W)) +
  geom_ribbon(aes(ymin = pred_Q2.5, ymax = pred_Q97.5),
              fill = "olivedrab1", alpha = 0.5) +
  geom_smooth(mapping = aes(y = fit, ymin = fit_Q2.5, ymax = fit_Q97.5),
              stat = "identity",
              fill = "olivedrab3", color = "olivedrab4", alpha = 0.5) +
  geom_point(aes(color = group)) +
  scale_color_paletteer_c("oompaBase::jetColors") + 
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = "Practice 6H1a: Weight vs Area Size",
       color = "group",
       x = "area size (std)", y = "weight (std)")
```


### 6H2 b) By group size {-}


$$
\begin{align*}
W_i &\sim \mathcal{N}(\mu_i, \sigma) \\
\mu_i &= \alpha + \beta \cdot S_i \\
\alpha &\sim \mathcal{N}(0, 0.5) \\
\beta &\sim \mathcal{N}(0, 0.2) \\
\sigma &\sim \mathcal{HalfCauchy}(0, 1)
\end{align*}
$$

and the fit

```{r}
a_file <- here::here("fits", "b06H02b.rds")
b06H02b <- readRDS(file = a_file)
# b06H02b <- brm(
#   data = d,
#   formula = W ~ 1 + S,
#   family = gaussian(),
#   prior = c(
#     prior(normal(0, 0.5), class = Intercept),
#     prior(normal(0, 0.2), class = b),
#     prior(cauchy(0, 1), class = sigma)
#   ),
#   iter = 2000, warmup = 1000, chains = 4, core = detectCores(),
#   seed = 6
# )
# saveRDS(b06H02b, file = a_file)
summary(b06H02b)
```

and create the full data for plotting

```{r}
samples <- list()
samples$fitted <- fitted(b06H02b) %>%
  as.data.frame() %>%
  rename(
    fit = Estimate,
    fit_err = Est.Error,
    fit_Q2.5 = Q2.5,
    fit_Q97.5 = Q97.5)

samples$predict <- predict(b06H02b) %>%
  data.frame() %>%
  rename(
    pred = Estimate,
    pred_err = Est.Error,
    pred_Q2.5 = Q2.5,
    pred_Q97.5 = Q97.5,)

samples$data <- d %>%
  bind_cols(samples$fitted) %>%
  bind_cols(samples$predict)
```



```{r}
ggplot(data = samples$data, mapping = aes(x = S, y = W)) +
  geom_ribbon(aes(ymin = pred_Q2.5, ymax = pred_Q97.5),
              fill = "thistle1", alpha = 0.5) +
  geom_smooth(mapping = aes(y = fit, ymin = fit_Q2.5, ymax = fit_Q97.5),
              stat = "identity",
              fill = "thistle3", color = "thistle4", alpha = 0.5) +
  geom_point(aes(color = group)) +
  scale_color_paletteer_c("oompaBase::jetColors") + 
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = "Practice 6H2b: Weight vs Group Size",
       color = "group",
       x = "group size (std)", y = "weight (std)")
```



